apiVersion: v2
name: servas
description: A Helm chart for Kubernetes
type: application

version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: mariadb
    version: 20.4.2
    repository: https://charts.bitnami.com/bitnami
